export const moviePopular = [
  {
    adult: false,
    backdrop_path: '/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg',
    genre_ids: [35, 28, 12, 878],
    id: 550988,
    original_language: 'en',
    original_title: 'Free Guy',
    overview:
      'A bank teller called Guy realizes he is a background character in an open world video game called Free City that will soon go offline.',
    popularity: 13250.324,
    poster_path: '/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg',
    release_date: '2021-08-11',
    title: 'Free Guy',
    video: false,
    vote_average: 8,
    vote_count: 1977,
  },
  {
    adult: false,
    backdrop_path: '/aO9Nnv9GdwiPdkNO79TISlQ5bbG.jpg',
    genre_ids: [28, 12],
    id: 568620,
    original_language: 'en',
    original_title: 'Snake Eyes: G.I. Joe Origins',
    overview:
      "After saving the life of their heir apparent, tenacious loner Snake Eyes is welcomed into an ancient Japanese clan called the Arashikage where he is taught the ways of the ninja warrior. But, when secrets from his past are revealed, Snake Eyes' honor and allegiance will be tested – even if that means losing the trust of those closest to him.",
    popularity: 7692.29,
    poster_path: '/uIXF0sQGXOxQhbaEaKOi2VYlIL0.jpg',
    release_date: '2021-07-22',
    title: 'Snake Eyes: G.I. Joe Origins',
    video: false,
    vote_average: 7,
    vote_count: 558,
  },
  {
    adult: false,
    backdrop_path: '/owraiceOKtSOa3t8sp3wA9K2Ox6.jpg',
    genre_ids: [16, 28, 12, 878],
    id: 703771,
    original_language: 'en',
    original_title: 'Deathstroke: Knights & Dragons - The Movie',
    overview:
      'The assassin Deathstroke tries to save his family from the wrath of H.I.V.E. and the murderous Jackal.',
    popularity: 5841.184,
    poster_path: '/vFIHbiy55smzi50RmF8LQjmpGcx.jpg',
    release_date: '2020-08-04',
    title: 'Deathstroke: Knights & Dragons - The Movie',
    video: false,
    vote_average: 7,
    vote_count: 250,
  },
  {
    adult: false,
    backdrop_path: '/umAoDwLZMBrYeCDfbJYFRMuXWAr.jpg',
    genre_ids: [878],
    id: 681887,
    original_language: 'en',
    original_title: 'Cosmic Sin',
    overview:
      "In the year 2524, four centuries after humans started colonizing the outer planets, retired General James Ford gets called back into service when a hostile alien fleet attacks soldiers on a remote planet. The threat against mankind soon escalates into an interstellar war as Ford and a team of elite soldiers try to stop the imminent attack before it's too late.",
    popularity: 5385.236,
    poster_path: '/6Wm7P6y22UZA40QuPYHyWyJ6leI.jpg',
    release_date: '2021-03-12',
    title: 'Cosmic Sin',
    video: false,
    vote_average: 4.5,
    vote_count: 306,
  },
  {
    adult: false,
    backdrop_path: '/vkIJ2QgcKMJRvi6pBW4Tr2kgLdy.jpg',
    genre_ids: [80, 53],
    id: 637534,
    original_language: 'fr',
    original_title: 'BAC Nord',
    overview:
      'A police brigade working in the dangerous northern neighborhoods of Marseille, where the level of crime is higher than anywhere else in France.',
    popularity: 4253.901,
    poster_path: '/nLanxl7Xhfbd5s8FxPy8jWZw4rv.jpg',
    release_date: '2021-08-18',
    title: 'The Stronghold',
    video: false,
    vote_average: 7.8,
    vote_count: 367,
  },
  {
    adult: false,
    backdrop_path: '/t9nyF3r0WAlJ7Kr6xcRYI4jr9jm.jpg',
    genre_ids: [878, 28],
    id: 580489,
    original_language: 'en',
    original_title: 'Venom: Let There Be Carnage',
    overview:
      'After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.',
    popularity: 4225.219,
    poster_path: '/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg',
    release_date: '2021-09-30',
    title: 'Venom: Let There Be Carnage',
    video: false,
    vote_average: 7.4,
    vote_count: 142,
  },
  {
    adult: false,
    backdrop_path: '/dIibeeq4QMay5bTJ2vjr72IFFRo.jpg',
    genre_ids: [14, 12, 35],
    id: 589754,
    original_language: 'ru',
    original_title: 'Последний богатырь: Корень зла',
    overview:
      'Peace and tranquility have set in Belogorie. The evil was defeated and Ivan is now enjoying his well-deserved fame. He is surrounded by his family, friends and small wonders from the modern world that help him lead a comfortable life. Luckily, he has his Magic Sword to cut a gap between the worlds to get some supplies quite regularly. But when an ancient evil rises and the existence of the magic world is put to danger, Ivan has to team up with his old friends and his new rivals. They will set out on a long journey beyond the known world to find a way to defeat the enemies and to return peace to Belogorie.',
    popularity: 3485.444,
    poster_path: '/5VJSIAhSn4qUsg5nOj4MhQhF5wQ.jpg',
    release_date: '2021-01-01',
    title: 'The Last Warrior: Root of Evil',
    video: false,
    vote_average: 7.1,
    vote_count: 40,
  },
  {
    adult: false,
    backdrop_path: '/5PQhNs4M3RxIqaNAdBI6mXlXyYh.jpg',
    genre_ids: [27, 14, 9648],
    id: 839436,
    original_language: 'en',
    original_title: 'Dragon Fury',
    overview:
      'A group of soldiers are taken to the mountains of Wales to investigate a strange beast.',
    popularity: 2928.638,
    poster_path: '/6WcJ4cV2Y3gnTYp5zHu968TYmTJ.jpg',
    release_date: '2021-06-15',
    title: 'Dragon Fury',
    video: false,
    vote_average: 4.2,
    vote_count: 8,
  },
  {
    adult: false,
    backdrop_path: '/cinER0ESG0eJ49kXlExM0MEWGxW.jpg',
    genre_ids: [28, 12, 14],
    id: 566525,
    original_language: 'en',
    original_title: 'Shang-Chi and the Legend of the Ten Rings',
    overview:
      'Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.',
    popularity: 2036.745,
    poster_path: '/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg',
    release_date: '2021-09-01',
    title: 'Shang-Chi and the Legend of the Ten Rings',
    video: false,
    vote_average: 7.8,
    vote_count: 1152,
  },
  {
    adult: false,
    backdrop_path: '/iTgM25ftE7YtFgZwUZupVp8A61S.jpg',
    genre_ids: [27, 9648, 53],
    id: 631843,
    original_language: 'en',
    original_title: 'Old',
    overview:
      'A group of families on a tropical holiday discover that the secluded beach where they are staying is somehow causing them to age rapidly – reducing their entire lives into a single day.',
    popularity: 1818.494,
    poster_path: '/vclShucpUmPhdAOmKgf3B3Z4POD.jpg',
    release_date: '2021-07-21',
    title: 'Old',
    video: false,
    vote_average: 6.7,
    vote_count: 1053,
  },
  {
    adult: false,
    backdrop_path: '/iDLtDgxLiYsarfdQ4msUhUqoNPp.jpg',
    genre_ids: [878],
    id: 725273,
    original_language: 'en',
    original_title: 'Solitary',
    overview:
      "A man wakes up inside a room to discover he's a prisoner sent into space to form Earth's first colony, and worse - his cell mate Alana is hell bent on destroying everything.",
    popularity: 2341.014,
    poster_path: '/ApwmbrMlsuOay5rXQA4Kbz7qJAl.jpg',
    release_date: '2021-09-24',
    title: 'Solitary',
    video: false,
    vote_average: 6.8,
    vote_count: 23,
  },
  {
    adult: false,
    backdrop_path: '/3GgkzCDq6KYpcmJmcOKh27hYRyj.jpg',
    genre_ids: [12, 16, 10751, 14],
    id: 588921,
    original_language: 'en',
    original_title: 'Ainbo: Spirit of the Amazon',
    overview: '',
    popularity: 1535.623,
    poster_path: '/l8HyObVj8fPrzacAPtGWWLDhcfh.jpg',
    release_date: '2021-02-09',
    title: 'Ainbo: Spirit of the Amazon',
    video: false,
    vote_average: 7.3,
    vote_count: 184,
  },
  {
    adult: false,
    backdrop_path: '/VuukZLgaCrho2Ar8Scl9HtV3yD.jpg',
    genre_ids: [878, 28],
    id: 335983,
    original_language: 'en',
    original_title: 'Venom',
    overview:
      'Investigative journalist Eddie Brock attempts a comeback following a scandal, but accidentally becomes the host of Venom, a violent, super powerful alien symbiote. Soon, he must rely on his newfound powers to protect the world from a shadowy organization looking for a symbiote of their own.',
    popularity: 1825.25,
    poster_path: '/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg',
    release_date: '2018-09-28',
    title: 'Venom',
    video: false,
    vote_average: 6.8,
    vote_count: 11476,
  },
  {
    adult: false,
    backdrop_path: '/jlGmlFOcfo8n5tURmhC7YVd4Iyy.jpg',
    genre_ids: [28, 12, 14, 35],
    id: 436969,
    original_language: 'en',
    original_title: 'The Suicide Squad',
    overview:
      'Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.',
    popularity: 1723.518,
    poster_path: '/kb4s0ML0iVZlG6wAKbbs9NAm6X.jpg',
    release_date: '2021-07-28',
    title: 'The Suicide Squad',
    video: false,
    vote_average: 7.8,
    vote_count: 4205,
  },
  {
    adult: false,
    backdrop_path: '/MDYanFolbT76dj0gsCbhS2GM5A.jpg',
    genre_ids: [37, 28],
    id: 859860,
    original_language: 'en',
    original_title: 'Catch the Bullet',
    overview:
      'U.S. marshal Britt MacMasters returns from a mission to find his father wounded and his son kidnapped by the outlaw Jed Blake. Hot on their trail, Britt forms a posse with a gunslinging deputy and a stoic Pawnee tracker. But Jed and Britt tread dangerously close to the Red Desert’s Sioux territory.',
    popularity: 1653.838,
    poster_path: '/qKxrBZ8Ts4KHZKp7BT6GAVMLFO2.jpg',
    release_date: '2021-09-10',
    title: 'Catch the Bullet',
    video: false,
    vote_average: 5.6,
    vote_count: 46,
  },
  {
    adult: false,
    backdrop_path: '/7WJjFviFBffEJvkAms4uWwbcVUk.jpg',
    genre_ids: [12, 14, 35, 28],
    id: 451048,
    original_language: 'en',
    original_title: 'Jungle Cruise',
    overview:
      'Dr. Lily Houghton enlists the aid of wisecracking skipper Frank Wolff to take her down the Amazon in his dilapidated boat. Together, they search for an ancient tree that holds the power to heal – a discovery that will change the future of medicine.',
    popularity: 1710.16,
    poster_path: '/9dKCd55IuTT5QRs989m9Qlb7d2B.jpg',
    release_date: '2021-07-28',
    title: 'Jungle Cruise',
    video: false,
    vote_average: 7.8,
    vote_count: 2807,
  },
  {
    adult: false,
    backdrop_path: '/ugukqzx4gSzBd1yzmbWEHLkpGaS.jpg',
    genre_ids: [16, 10751, 14, 35, 10402, 12],
    id: 597316,
    original_language: 'en',
    original_title: 'My Little Pony: A New Generation',
    overview:
      "Equestria's divided. But a bright-eyed hero believes Earth Ponies, Pegasi and Unicorns should be pals — and, hoof to heart, she’s determined to prove it.",
    popularity: 1407.579,
    poster_path: '/hzq5XRGgm6NDMOW1idUvbpGqEkv.jpg',
    release_date: '2021-09-23',
    title: 'My Little Pony: A New Generation',
    video: false,
    vote_average: 8,
    vote_count: 74,
  },
  {
    adult: false,
    backdrop_path: '/byflnwPMumyvrCW9SfO5Miq3647.jpg',
    genre_ids: [28, 53],
    id: 597891,
    original_language: 'en',
    original_title: 'Kate',
    overview:
      "After she's irreversibly poisoned, a ruthless criminal operative has less than 24 hours to exact revenge on her enemies and in the process forms an unexpected bond with the daughter of one of her past victims.",
    popularity: 1437.507,
    poster_path: '/uJgdT1boTSP0dDIjdTgGleg71l4.jpg',
    release_date: '2021-09-10',
    title: 'Kate',
    video: false,
    vote_average: 6.8,
    vote_count: 570,
  },
  {
    adult: false,
    backdrop_path: '/pUc51UUQb1lMLVVkDCaZVsCo37U.jpg',
    genre_ids: [53, 27],
    id: 482373,
    original_language: 'en',
    original_title: "Don't Breathe 2",
    overview:
      'The Blind Man has been hiding out for several years in an isolated cabin and has taken in and raised a young girl orphaned from a devastating house fire. Their quiet life together is shattered when a group of criminals kidnap the girl, forcing the Blind Man to leave his safe haven to save her.',
    popularity: 1449.03,
    poster_path: '/hRMfgGFRAZIlvwVWy8DYJdLTpvN.jpg',
    release_date: '2021-08-12',
    title: "Don't Breathe 2",
    video: false,
    vote_average: 7.7,
    vote_count: 853,
  },
  {
    adult: false,
    backdrop_path: '/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg',
    genre_ids: [28, 80, 53],
    id: 385128,
    original_language: 'en',
    original_title: 'F9',
    overview:
      "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
    popularity: 1553.717,
    poster_path: '/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg',
    release_date: '2021-05-19',
    title: 'F9',
    video: false,
    vote_average: 7.5,
    vote_count: 3901,
  },
];
export const movieUpcoming = [
  {
    adult: false,
    backdrop_path: '/aO9Nnv9GdwiPdkNO79TISlQ5bbG.jpg',
    genre_ids: [28, 12],
    id: 568620,
    original_language: 'en',
    original_title: 'Snake Eyes: G.I. Joe Origins',
    overview:
      "After saving the life of their heir apparent, tenacious loner Snake Eyes is welcomed into an ancient Japanese clan called the Arashikage where he is taught the ways of the ninja warrior. But, when secrets from his past are revealed, Snake Eyes' honor and allegiance will be tested – even if that means losing the trust of those closest to him.",
    popularity: 7692.29,
    poster_path: '/uIXF0sQGXOxQhbaEaKOi2VYlIL0.jpg',
    release_date: '2021-07-22',
    title: 'Snake Eyes: G.I. Joe Origins',
    video: false,
    vote_average: 7,
    vote_count: 558,
  },
  {
    adult: false,
    backdrop_path: '/t9nyF3r0WAlJ7Kr6xcRYI4jr9jm.jpg',
    genre_ids: [878, 28],
    id: 580489,
    original_language: 'en',
    original_title: 'Venom: Let There Be Carnage',
    overview:
      'After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.',
    popularity: 4225.219,
    poster_path: '/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg',
    release_date: '2021-09-30',
    title: 'Venom: Let There Be Carnage',
    video: false,
    vote_average: 7.4,
    vote_count: 142,
  },
  {
    adult: false,
    backdrop_path: '/akwg1s7hV5ljeSYFfkw7hTHjVqk.jpg',
    genre_ids: [16, 35, 12, 10751],
    id: 459151,
    original_language: 'en',
    original_title: 'The Boss Baby: Family Business',
    overview:
      'The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.',
    popularity: 1251.776,
    poster_path: '/uWStkK8bq9ixY3fc7y209ZleCoF.jpg',
    release_date: '2021-07-01',
    title: 'The Boss Baby: Family Business',
    video: false,
    vote_average: 7.7,
    vote_count: 1461,
  },
  {
    adult: false,
    backdrop_path: '/qD45xHA35HdJDGOaA1AgDwiWEgO.jpg',
    genre_ids: [10749, 18],
    id: 744275,
    original_language: 'en',
    original_title: 'After We Fell',
    overview:
      "Just as Tessa's life begins to become unglued, nothing is what she thought it would be. Not her friends nor her family. The only person that she should be able to rely on is Hardin, who is furious when he discovers the massive secret that she's been keeping. Before Tessa makes the biggest decision of her life, everything changes because of revelations about her family.",
    popularity: 917.035,
    poster_path: '/3WfvjNWr5k1Zzww81b3GWc8KQhb.jpg',
    release_date: '2021-09-01',
    title: 'After We Fell',
    video: false,
    vote_average: 8.1,
    vote_count: 297,
  },
  {
    adult: false,
    backdrop_path: '/kcvKEvTWqIGMjpVJdbDVRHdIt4C.jpg',
    genre_ids: [12, 28, 53],
    id: 370172,
    original_language: 'en',
    original_title: 'No Time to Die',
    overview:
      'Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.',
    popularity: 926.964,
    poster_path: '/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg',
    release_date: '2021-09-29',
    title: 'No Time to Die',
    video: false,
    vote_average: 7.3,
    vote_count: 187,
  },
  {
    adult: false,
    backdrop_path: '/3pIqd1hgZ2xqzWEyiYp4blqE9Fi.jpg',
    genre_ids: [53, 18, 36],
    id: 522241,
    original_language: 'en',
    original_title: 'The Courier',
    overview:
      'Cold War spy Greville Wynne and his Russian source try to put an end to the Cuban Missile Crisis.',
    popularity: 957.748,
    poster_path: '/zFIjKtZrzhmc7HecdFXXjsLR2Ig.jpg',
    release_date: '2021-03-18',
    title: 'The Courier',
    video: false,
    vote_average: 7.1,
    vote_count: 402,
  },
  {
    adult: false,
    backdrop_path: '/mHU833IrBRfZ3hhzEQsiiw2D8Nc.jpg',
    genre_ids: [27, 53],
    id: 565028,
    original_language: 'en',
    original_title: 'Candyman',
    overview:
      'Anthony and his partner move into a loft in the now gentrified Cabrini-Green, and after a chance encounter with an old-timer exposes Anthony to the true story behind Candyman, he unknowingly opens a door to a complex past that unravels his own sanity and unleashes a terrifying wave of violence.',
    popularity: 746.923,
    poster_path: '/dqoshZPLNsXlC1qtz5n34raUyrE.jpg',
    release_date: '2021-08-25',
    title: 'Candyman',
    video: false,
    vote_average: 6.5,
    vote_count: 399,
  },
  {
    adult: false,
    backdrop_path: '/fRrpOILyXuWaWLmqF7kXeMVwITQ.jpg',
    genre_ids: [27, 53, 12, 9648],
    id: 522444,
    original_language: 'en',
    original_title: 'Black Water: Abyss',
    overview:
      'An adventure-loving couple convince their friends to explore a remote, uncharted cave system in the forests of Northern Australia. With a tropical storm approaching, they abseil into the mouth of the cave, but when the caves start to flood, tensions rise as oxygen levels fall and the friends find themselves trapped. Unknown to them, the storm has also brought in a pack of dangerous and hungry crocodiles.',
    popularity: 487.282,
    poster_path: '/95S6PinQIvVe4uJAd82a2iGZ0rA.jpg',
    release_date: '2020-07-09',
    title: 'Black Water: Abyss',
    video: false,
    vote_average: 5.1,
    vote_count: 271,
  },
  {
    adult: false,
    backdrop_path: '/aknvFyJUQQoZFtmFnYzKi4vGv4J.jpg',
    genre_ids: [28, 12, 18, 878],
    id: 438631,
    original_language: 'en',
    original_title: 'Dune',
    overview:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    popularity: 440.052,
    poster_path: '/s1FhMAr91WL8D5DeHOcuBELtiHJ.jpg',
    release_date: '2021-09-15',
    title: 'Dune',
    video: false,
    vote_average: 8.1,
    vote_count: 1278,
  },
  {
    adult: false,
    backdrop_path: '/g6wufgtycJCP508tlC3crSYFCgC.jpg',
    genre_ids: [37, 18],
    id: 749274,
    original_language: 'en',
    original_title: 'Cry Macho',
    overview:
      "Mike Milo, a one-time rodeo star and washed-up horse breeder, takes a job from an ex-boss to bring the man's young son home from Mexico.",
    popularity: 232.179,
    poster_path: '/wqaaWAlXgLNGdAemU7wNvFZ70hr.jpg',
    release_date: '2021-09-16',
    title: 'Cry Macho',
    video: false,
    vote_average: 6.8,
    vote_count: 145,
  },
  {
    adult: false,
    backdrop_path: '/kTOheVmqSBDIRGrQLv2SiSc89os.jpg',
    genre_ids: [16, 35, 10751],
    id: 639721,
    original_language: 'en',
    original_title: 'The Addams Family 2',
    overview:
      'The Addams get tangled up in more wacky adventures and find themselves involved in hilarious run-ins with all sorts of unsuspecting characters.',
    popularity: 280.58,
    poster_path: '/xYLBgw7dHyEqmcrSk2Sq3asuSq5.jpg',
    release_date: '2021-10-01',
    title: 'The Addams Family 2',
    video: false,
    vote_average: 8,
    vote_count: 77,
  },
  {
    adult: false,
    backdrop_path: '/5MlvT4DZIdkpb7A9t375HVoiJ1v.jpg',
    genre_ids: [28, 12, 18, 53],
    id: 646207,
    original_language: 'en',
    original_title: 'The Ice Road',
    overview:
      'After a remote diamond mine collapses in far northern Canada, an ice road driver must lead an impossible rescue mission over a frozen ocean to save the trapped miners.',
    popularity: 185.507,
    poster_path: '/eOH9yh5r7QD4n94gbp7kULf2ft6.jpg',
    release_date: '2021-06-24',
    title: 'The Ice Road',
    video: false,
    vote_average: 7.2,
    vote_count: 676,
  },
  {
    adult: false,
    backdrop_path: '/2RHjd10wqv57xYzZkNK8Sl09Ddt.jpg',
    genre_ids: [16, 28, 35, 14, 12],
    id: 768744,
    original_language: 'ja',
    original_title:
      '僕のヒーローアカデミア THE MOVIE ワールド ヒーローズ ミッション',
    overview:
      'A mysterious group called Humarize strongly believes in the Quirk Singularity Doomsday theory which states that when quirks get mixed further in with future generations, that power will bring forth the end of humanity. In order to save everyone, the Pro-Heroes around the world ask UA Academy heroes-in-training to assist them and form a world-classic selected hero team. It is up to the heroes to save the world and the future of heroes in what is the most dangerous crisis to take place yet in My Hero Academy.',
    popularity: 149.072,
    poster_path: '/yjdOpEtlzlAnw4Kw0NGw25VrbIb.jpg',
    release_date: '2021-08-06',
    title: "My Hero Academia: World Heroes' Mission",
    video: false,
    vote_average: 6.9,
    vote_count: 11,
  },
  {
    adult: false,
    backdrop_path: '/4Tz8V8aRim8cFgKEWprSUjBy8tY.jpg',
    genre_ids: [18, 10402, 10749],
    id: 776503,
    original_language: 'en',
    original_title: 'CODA',
    overview:
      "As a CODA (Child of Deaf Adults), Ruby is the only hearing person in her deaf family. When the family's fishing business is threatened, Ruby finds herself torn between pursuing her love of music and her fear of abandoning her parents.",
    popularity: 174.502,
    poster_path: '/BzVjmm8l23rPsijLiNLUzuQtyd.jpg',
    release_date: '2021-07-30',
    title: 'CODA',
    video: false,
    vote_average: 8.4,
    vote_count: 209,
  },
  {
    adult: false,
    backdrop_path: '/kIG81E0H4CxuYIRgyNyD0z3KSlM.jpg',
    genre_ids: [27, 53],
    id: 610253,
    original_language: 'en',
    original_title: 'Halloween Kills',
    overview:
      "Minutes after Laurie Strode, her daughter Karen and granddaughter Allyson leave the masked monster Michael Myers caged and burning in Laurie's basement, Laurie is rushed to the hospital with fatal injuries, believing she has finally killed her algorithm.  But when Michael manages to free himself from Laurie's trap, his bloodbath ritual begins again. As Laurie fights her pain and prepares to defend against it, she inspires everyone in Haddonfield to rise up against her unstoppable monster. But when a group of other survivors of Michael's first wave of violence decide to take matters into their own hands, a mob of vigilantes gathers to hunt Michael down.",
    popularity: 151.256,
    poster_path: '/1hT1HXhSgLHW3XEAcsgsZNfhbiY.jpg',
    release_date: '2021-10-14',
    title: 'Halloween Kills',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/r7dJqfmspzVlHYWXBiKn7NP8ZBw.jpg',
    genre_ids: [18, 53, 80],
    id: 643532,
    original_language: 'en',
    original_title: 'The Card Counter',
    overview:
      'William Tell just wants to play cards. His spartan existence on the casino trail is shattered when he is approached by Cirk, a vulnerable and angry young man seeking help to execute his plan for revenge on a military colonel. Tell sees a chance at redemption through his relationship with Cirk. But keeping Cirk on the straight-and-narrow proves impossible, dragging Tell back into the darkness of his past.',
    popularity: 109.854,
    poster_path: '/60AQOrByV9vDCqy6nt4eOroRild.jpg',
    release_date: '2021-09-03',
    title: 'The Card Counter',
    video: false,
    vote_average: 6.6,
    vote_count: 115,
  },
  {
    adult: false,
    backdrop_path: '/eBGKU0ZLJmxtVtzESTB1mfllX1J.jpg',
    genre_ids: [80, 28, 53],
    id: 630004,
    original_language: 'en',
    original_title: 'The Vault',
    overview:
      "When an engineer learns of a mysterious, impenetrable fortress hidden under The Bank of Spain, he joins a crew of master thieves who plan to steal the legendary lost treasure locked inside while the whole country is distracted by Spain's World Cup Final. With thousands of soccer fans cheering in the streets, and security forces closing in, the crew have just minutes to pull off the score of a lifetime.",
    popularity: 57.271,
    poster_path: '/iiHubBBVFg6K7t5THdsImqy1ct2.jpg',
    release_date: '2021-03-03',
    title: 'The Vault',
    video: false,
    vote_average: 7.1,
    vote_count: 298,
  },
  {
    adult: false,
    backdrop_path: '/hrzoy8vvUrxQixOM11pwW9AX7Bu.jpg',
    genre_ids: [80, 18],
    id: 524369,
    original_language: 'en',
    original_title: 'The Many Saints of Newark',
    overview:
      'Young Anthony Soprano is growing up in one of the most tumultuous eras in Newark, N.J., history, becoming a man just as rival gangsters start to rise up and challenge the all-powerful DiMeo crime family. Caught up in the changing times is the uncle he idolizes, Dickie Moltisanti, whose influence over his nephew will help shape the impressionable teenager into the all-powerful mob boss, Tony Soprano.',
    popularity: 92.05,
    poster_path: '/1UkbPQspPbq1FPbFP4VV1ELCfSN.jpg',
    release_date: '2021-09-22',
    title: 'The Many Saints of Newark',
    video: false,
    vote_average: 6.8,
    vote_count: 39,
  },
  {
    adult: false,
    backdrop_path: '/tsfrGux8hdnoYBYXjuGS9Ef7Usv.jpg',
    genre_ids: [28, 53],
    id: 695080,
    original_language: 'en',
    original_title: 'American Night',
    overview:
      "A neo-noir set in the New York City's corrupt contemporary art world where the art dealer John Kaplan and the ruthless head of New York's mafia, Michael Rubino, fight for money, art, power and love.",
    popularity: 57.581,
    poster_path: '/wdIDoA18nbTO8Dux8LgsGLnwlvZ.jpg',
    release_date: '2021-10-01',
    title: 'American Night',
    video: false,
    vote_average: 7.8,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: '/2dWWf6qjVU0TklCUKCUra1Yqfz3.jpg',
    genre_ids: [18],
    id: 618416,
    original_language: 'en',
    original_title: 'Penguin Bloom',
    overview:
      "When an unlikely ally enters the Bloom family's world in the form of an injured baby magpie they name Penguin, the bird’s arrival makes a profound difference in the struggling family’s life.",
    popularity: 86.102,
    poster_path: '/iUn7594Rwfstu5njA8hf9WQIcFi.jpg',
    release_date: '2021-01-21',
    title: 'Penguin Bloom',
    video: false,
    vote_average: 7.2,
    vote_count: 135,
  },
];
export const tvPopular = [
  {
    backdrop_path: '/oaGvjB0DvdhXhOAuADfHb261ZHa.jpg',
    first_air_date: '2021-09-17',
    genre_ids: [10759, 9648, 18],
    id: 93405,
    name: 'Squid Game',
    origin_country: ['KR'],
    original_language: 'ko',
    original_name: '오징어 게임',
    overview:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes.",
    popularity: 13496.167,
    poster_path: '/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
    vote_average: 7.9,
    vote_count: 5726,
  },
  {
    backdrop_path: '/1c7zy6zUbZ2s4zFAy6CpKipQvdQ.jpg',
    first_air_date: '2019-01-11',
    genre_ids: [35, 18],
    id: 81356,
    name: 'Sex Education',
    origin_country: ['GB'],
    original_language: 'en',
    original_name: 'Sex Education',
    overview:
      'Inexperienced Otis channels his sex therapist mom when he teams up with rebellious Maeve to set up an underground sex therapy clinic at school.',
    popularity: 2525.848,
    poster_path: '/8j12tohv1NBZNmpU93f47sAKBbw.jpg',
    vote_average: 8.4,
    vote_count: 4724,
  },
  {
    backdrop_path: '/4N6zEMfZ57zNEQcM8gWeERFupMv.jpg',
    first_air_date: '2021-08-11',
    genre_ids: [16, 10759, 10765],
    id: 91363,
    name: 'What If...?',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'What If...?',
    overview:
      'Taking inspiration from the comic books of the same name, each episode explores a pivotal moment from the Marvel Cinematic Universe and turns it on its head, leading the audience into uncharted territory.',
    popularity: 2210.116,
    poster_path: '/lztz5XBMG1x6Y5ubz7CxfPFsAcW.jpg',
    vote_average: 8.5,
    vote_count: 2029,
  },
  {
    backdrop_path: '/2dFNC3tuX88FMw4WVzLJAhooPDy.jpg',
    first_air_date: '2019-08-16',
    genre_ids: [18],
    id: 90239,
    name: 'El Juego de las Llaves',
    origin_country: ['MX', 'US'],
    original_language: 'es',
    original_name: 'El Juego de las Llaves',
    overview:
      'A casual encounter between Adriana and Sergio, two former high school friends, triggers the beginning of the game of the keys where 4 couples generate new sexual and emotional combinations in a dangerous and lustful game.',
    popularity: 1923.758,
    poster_path: '/2cMy9qphoOLJjYJJJQBBul0d94q.jpg',
    vote_average: 7.4,
    vote_count: 1251,
  },
  {
    backdrop_path: '/nlor5UKEkOuARd6YcltbeVyOgUz.jpg',
    first_air_date: '2021-05-25',
    genre_ids: [10766],
    id: 124124,
    name: 'Café con aroma de mujer',
    origin_country: ['US'],
    original_language: 'es',
    original_name: 'Café con aroma de mujer',
    overview: '',
    popularity: 975.407,
    poster_path: '/ztyJqTdS7RApGgl6ZXmFdGZX3g0.jpg',
    vote_average: 6.9,
    vote_count: 17,
  },
  {
    backdrop_path: '/ktDJ21QQscbMNQfPpZBsNORxdDx.jpg',
    first_air_date: '2016-01-25',
    genre_ids: [80, 10765],
    id: 63174,
    name: 'Lucifer',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Lucifer',
    overview:
      "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
    popularity: 1439.681,
    poster_path: '/ekZobS8isE6mA53RAiGDG93hBxL.jpg',
    vote_average: 8.5,
    vote_count: 10573,
  },
  {
    backdrop_path: '/wvdWb5kTQipdMDqCclC6Y3zr4j3.jpg',
    first_air_date: '2010-10-31',
    genre_ids: [10759, 18, 10765],
    id: 1402,
    name: 'The Walking Dead',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'The Walking Dead',
    overview:
      "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
    popularity: 1189.779,
    poster_path: '/w21lgYIi9GeUH5dO8l3B9ARZbCB.jpg',
    vote_average: 8.1,
    vote_count: 11761,
  },
  {
    backdrop_path: '/5pTJNgwN3J1QeHIAse0LotDiAH7.jpg',
    first_air_date: '2021-09-08',
    genre_ids: [18],
    id: 133007,
    name: 'The Justice',
    origin_country: ['CN'],
    original_language: 'zh',
    original_name: '光芒',
    overview:
      "Set in 1930s Shanghai, Cheng Yi Zhi who comes from a poor family meets Wu Ru Fu, a banker and his daughter Li Zi. Inspired by Wu, Cheng Yi Zhi quits his job as a businessman and enters the finance industry; and becomes bank owner Boss Huang's closest confidante. However, he finds out that Boss Huang caused the death of Wu Ru Fu, and also colluded with various forces to build a black money empire. Cheng Yi Zhi decides to leave Boss Huang, and teams up with Li Zi to create a new bank industry. However they face opposition from Boss Huang and the Japanese. With the help of the underground party, Cheng Yi Zhi works together with the industry people to revitalize the republican.",
    popularity: 694.372,
    poster_path: '/9ocGQaAbHxRbQFipOfhRrq5BrFx.jpg',
    vote_average: 5,
    vote_count: 2,
  },
  {
    backdrop_path: '/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg',
    first_air_date: '2017-05-02',
    genre_ids: [80, 18],
    id: 71446,
    name: 'Money Heist',
    origin_country: ['ES'],
    original_language: 'es',
    original_name: 'La Casa de Papel',
    overview:
      'To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.',
    popularity: 1076.036,
    poster_path: '/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg',
    vote_average: 8.3,
    vote_count: 14605,
  },
  {
    backdrop_path: '/9OYu6oDLIidSOocW3JTGtd2Oyqy.jpg',
    first_air_date: '2017-09-25',
    genre_ids: [18],
    id: 71712,
    name: 'The Good Doctor',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'The Good Doctor',
    overview:
      "A young surgeon with Savant syndrome is recruited into the surgical unit of a prestigious hospital. The question will arise: can a person who doesn't have the ability to relate to people actually save their lives",
    popularity: 1362.872,
    poster_path: '/cXUqtadGsIcZDWUTrfnbDjAy8eN.jpg',
    vote_average: 8.6,
    vote_count: 9488,
  },
  {
    backdrop_path: '/ygAqLuy7nfOCKZ15BAvJvSkBjvG.jpg',
    first_air_date: '',
    genre_ids: [10764],
    id: 100128,
    name: 'Big Brother',
    origin_country: ['PT'],
    original_language: 'pt',
    original_name: 'Big Brother',
    overview:
      'Portuguese version of the reality competition which follows a group of HouseGuests living together 24 hours a day in the "Big Brother" house, isolated from the outside world but under constant surveillance with no privacy.',
    popularity: 1061.734,
    poster_path: '/9Gkcvdz89Q7w0glDDga1c8m5vaW.jpg',
    vote_average: 4.5,
    vote_count: 2,
  },
  {
    backdrop_path: '/qZtAf4Z1lazGQoYVXiHOrvLr5lI.jpg',
    first_air_date: '2017-01-26',
    genre_ids: [9648, 18, 80],
    id: 69050,
    name: 'Riverdale',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Riverdale',
    overview:
      'Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.',
    popularity: 863.022,
    poster_path: '/wRbjVBdDo5qHAEOVYoMWpM58FSA.jpg',
    vote_average: 8.6,
    vote_count: 11963,
  },
  {
    backdrop_path: '/gIApbx2ffXVhJb2D4tiEx2b06nl.jpg',
    first_air_date: '2005-03-27',
    genre_ids: [18],
    id: 1416,
    name: "Grey's Anatomy",
    origin_country: ['US'],
    original_language: 'en',
    original_name: "Grey's Anatomy",
    overview:
      'Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.',
    popularity: 769.63,
    poster_path: '/clnyhPqj1SNgpAdeSS6a6fwE6Bo.jpg',
    vote_average: 8.2,
    vote_count: 6785,
  },
  {
    backdrop_path: '/l8v3gJDlASN0lNn51gR8zQJsu5O.jpg',
    first_air_date: '2013-09-12',
    genre_ids: [80, 18],
    id: 60574,
    name: 'Peaky Blinders',
    origin_country: ['GB'],
    original_language: 'en',
    original_name: 'Peaky Blinders',
    overview:
      'A gangster family epic set in 1919 Birmingham, England and centered on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby, who means to move up in the world.',
    popularity: 715.956,
    poster_path: '/bGZn5RVzMMXju4ev7xbl1aLdXqq.jpg',
    vote_average: 8.6,
    vote_count: 3775,
  },
  {
    backdrop_path: '/eyG9srihv68ScRdEbJZj66WT4O0.jpg',
    first_air_date: '2014-10-07',
    genre_ids: [18, 10765],
    id: 60735,
    name: 'The Flash',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'The Flash',
    overview:
      'After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only "meta-human" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won\'t be long before the world learns what Barry Allen has become...The Flash.',
    popularity: 714.749,
    poster_path: '/lJA2RCMfsWoskqlQhXPSLFQGXEJ.jpg',
    vote_average: 7.8,
    vote_count: 8497,
  },
  {
    backdrop_path: '/bZGAX8oMDm3Mo5i0ZPKh9G2OcaO.jpg',
    first_air_date: '2021-06-09',
    genre_ids: [18, 10765],
    id: 84958,
    name: 'Loki',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Loki',
    overview:
      'After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant” or help fix the timeline and stop a greater threat.',
    popularity: 702,
    poster_path: '/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg',
    vote_average: 8.2,
    vote_count: 7792,
  },
  {
    backdrop_path: '/adZ9ldSlkGfLfsHNbh37ZThCcgU.jpg',
    first_air_date: '1989-12-17',
    genre_ids: [10751, 16, 35],
    id: 456,
    name: 'The Simpsons',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'The Simpsons',
    overview:
      'Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.',
    popularity: 480.928,
    poster_path: '/tubgEpjTUA7t0kejVMBsNBZDarZ.jpg',
    vote_average: 7.9,
    vote_count: 7101,
  },
  {
    backdrop_path: '/oSznw7CsnnG7rB21iNXooJaKVHO.jpg',
    first_air_date: '2013-12-02',
    genre_ids: [16, 35, 10765, 10759],
    id: 60625,
    name: 'Rick and Morty',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Rick and Morty',
    overview:
      "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
    popularity: 614.559,
    poster_path: '/8kOWDBK6XlPUzckuHDo3wwVRFwt.jpg',
    vote_average: 8.8,
    vote_count: 5546,
  },
  {
    backdrop_path: '/oKxrDdG0SfmWRtJYmreK4rjDMUo.jpg',
    first_air_date: '2019-11-01',
    genre_ids: [18, 10765, 10759],
    id: 80752,
    name: 'See',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'See',
    overview:
      'A virus has decimated humankind. Those who survived emerged blind. Centuries later when twins are born with the mythic ability to see, their father must protect his tribe against a threatened queen.',
    popularity: 568.52,
    poster_path: '/A6dnHWe8YYcoFBHzP7T6WPP4b6F.jpg',
    vote_average: 8.2,
    vote_count: 1219,
  },
  {
    backdrop_path: '/8sdFdIdShfQboyyMNAMxnHGWEEe.jpg',
    first_air_date: '2021-09-24',
    genre_ids: [80, 10759],
    id: 130523,
    name: 'Ganglands',
    origin_country: ['FR'],
    original_language: 'fr',
    original_name: 'Braqueurs: La série',
    overview:
      'Mehdi, a qualified robber, and Liana, an apprentice thief, get involved in a turf war between drug dealers, and have to collaborate in order to save their loved ones.',
    popularity: 717.35,
    poster_path: '/dC4ev3UuiIYPJCx65bU4GkmWx9S.jpg',
    vote_average: 7.6,
    vote_count: 17,
  },
];
export const tvTopData = [
  {
    backdrop_path: '/7q448EVOnuE3gVAx24krzO7SNXM.jpg',
    first_air_date: '2021-09-03',
    genre_ids: [99],
    id: 130392,
    name: "The D'Amelio Show",
    origin_country: ['US'],
    original_language: 'en',
    original_name: "The D'Amelio Show",
    overview:
      'From relative obscurity and a seemingly normal life, to overnight success and thrust into the Hollywood limelight overnight, the D’Amelios are faced with new challenges and opportunities they could not have imagined.',
    popularity: 31.74,
    poster_path: '/z0iCS5Znx7TeRwlYSd4c01Z0lFx.jpg',
    vote_average: 9.5,
    vote_count: 2439,
  },
  {
    backdrop_path: null,
    first_air_date: '2004-05-10',
    genre_ids: [16, 35],
    id: 100,
    name: 'I Am Not an Animal',
    origin_country: ['GB'],
    original_language: 'en',
    original_name: 'I Am Not an Animal',
    overview:
      'I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.',
    popularity: 10.107,
    poster_path: '/qG59J1Q7rpBc1dvku4azbzcqo8h.jpg',
    vote_average: 9.2,
    vote_count: 667,
  },
  {
    backdrop_path: '/c8dm74uPCMA27iKAR1WnHKTsI9h.jpg',
    first_air_date: '2015-08-01',
    genre_ids: [10764],
    id: 77696,
    name: 'Run BTS!',
    origin_country: ['KR'],
    original_language: 'ko',
    original_name: '달려라 방탄!',
    overview:
      'Run BTS! is a South Korean show by the boy band BTS. The show is all about BTS doing activities, challenges and lots more.',
    popularity: 45.63,
    poster_path: '/xxv8Ibs8Anni6qrWkAf60rDsPCu.jpg',
    vote_average: 9.2,
    vote_count: 191,
  },
  {
    backdrop_path: '/esMo90QAVfOpSVTUiCuhmDTnc5y.jpg',
    first_air_date: '2021-07-01',
    genre_ids: [18],
    id: 125910,
    name: 'Young Royals',
    origin_country: ['SE'],
    original_language: 'sv',
    original_name: 'Young Royals',
    overview:
      'Prince Wilhelm adjusts to life at his prestigious new boarding school, Hillerska, but following his heart proves more challenging than anticipated.',
    popularity: 54.509,
    poster_path: '/6CHznbr0BF78ar16zJwTVRYLLOX.jpg',
    vote_average: 9.1,
    vote_count: 456,
  },
  {
    backdrop_path: '/ohOrfdh80HVY5QBD8kV2FYYSVwF.jpg',
    first_air_date: '2021-01-10',
    genre_ids: [16, 10759],
    id: 110309,
    name: 'SK8 the Infinity',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'SK∞ エスケーエイト',
    overview:
      '"S" is a dangerous, top secret, no-holds-barred downhill skateboarding race down an abandoned mine. When avid skateboarder Reki takes Langa to the mountain where "S" is held, Langa, who\'s never been on a skateboard in his life, finds himself sucked into the world of "S", and…?!',
    popularity: 57.348,
    poster_path: '/ksb6QlSCsRLr3MNmxc8ojOOLK6V.jpg',
    vote_average: 9,
    vote_count: 136,
  },
  {
    backdrop_path: '/7gbmM2NWcqZONbp65HUWDf4wr0Q.jpg',
    first_air_date: '2019-07-12',
    genre_ids: [16, 18],
    id: 88040,
    name: 'Given',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'ギヴン',
    overview:
      "Tightly clutching his Gibson guitar, Mafuyu Satou steps out of his dark apartment to begin another day of his high school life. While taking a nap in a quiet spot on the gymnasium staircase, he has a chance encounter with fellow student Ritsuka Uenoyama, who berates him for letting his guitar's strings rust and break. Noticing Uenoyama's knowledge of the instrument, Satou pleads for him to fix it and to teach him how to play. Uenoyama eventually agrees and invites him to sit in on a jam session with his two band mates: bassist Haruki Nakayama and drummer Akihiko Kaji.",
    popularity: 41.907,
    poster_path: '/pdDCcAq8RNSZNk81PXYoHNUPHjn.jpg',
    vote_average: 9,
    vote_count: 534,
  },
  {
    backdrop_path: '/qSgBzXdu6QwVVeqOYOlHolkLRxZ.jpg',
    first_air_date: '2019-01-09',
    genre_ids: [16, 10759, 10765, 18],
    id: 83095,
    name: 'The Rising of the Shield Hero',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '盾の勇者の成り上がり',
    overview:
      "Iwatani Naofumi was summoned into a parallel world along with 3 other people to become the world's Heroes. Each of the heroes respectively equipped with their own legendary equipment when summoned, Naofumi received the Legendary Shield as his weapon. Due to Naofumi's lack of charisma and experience he's labeled as the weakest, only to end up betrayed, falsely accused, and robbed by on the third day of adventure. Shunned by everyone from the king to peasants, Naofumi's thoughts were filled with nothing but vengeance and hatred. Thus, his destiny in a parallel World begins...",
    popularity: 55.617,
    poster_path: '/6cXf5EDwVhsRv8GlBzUTVnWuk8Z.jpg',
    vote_average: 9,
    vote_count: 644,
  },
  {
    backdrop_path: '/uAjMQlbPkVHmUahhCouANlHSDW2.jpg',
    first_air_date: '2019-01-11',
    genre_ids: [16, 9648, 10765, 10759, 18],
    id: 83097,
    name: 'The Promised Neverland',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '約束のネバーランド',
    overview:
      'Surrounded by a forest and a gated entrance, the Grace Field House is inhabited by orphans happily living together as one big family, looked after by their "Mama," Isabella. Although they are required to take tests daily, the children are free to spend their time as they see fit, usually playing outside, as long as they do not venture too far from the orphanage — a rule they are expected to follow no matter what. However, all good times must come to an end, as every few months, a child is adopted and sent to live with their new family... never to be heard from again.\n\nHowever, the three oldest siblings have their suspicions about what is actually happening at the orphanage, and they are about to discover the cruel fate that awaits the children living at Grace Field, including the twisted nature of their beloved Mama.',
    popularity: 71.727,
    poster_path: '/oBgRCpAbtMpk1v8wfdsIph7lPQE.jpg',
    vote_average: 9,
    vote_count: 699,
  },
  {
    backdrop_path: '/nNqmwYbZKIxtgJ4TztF3QAKXIzx.jpg',
    first_air_date: '2021-08-31',
    genre_ids: [35, 80, 9648],
    id: 107113,
    name: 'Only Murders in the Building',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Only Murders in the Building',
    overview:
      'Three strangers who share an obsession with true crime suddenly find themselves wrapped up in one.',
    popularity: 461.63,
    poster_path: '/lxCmHIN7TTO0sxeAmgDYxqzq8Ob.jpg',
    vote_average: 9,
    vote_count: 277,
  },
  {
    backdrop_path: '/1ejS56lC8db62IKVj1pTQlfAEQy.jpg',
    first_air_date: '2018-09-13',
    genre_ids: [10759, 16, 18, 10751],
    id: 123566,
    name: 'Metal Family',
    origin_country: ['RU'],
    original_language: 'ru',
    original_name: 'Metal Family',
    overview:
      'Metal Family follows the daily lives of Glam and Victoria, two metal fans that fell in love and had two children together, Dee and Heavy.',
    popularity: 45.34,
    poster_path: '/yovTSLBdNjXIVo8CPaPWFE5NcAw.jpg',
    vote_average: 8.9,
    vote_count: 184,
  },
  {
    backdrop_path: '/ci7jTekDFEx6U48XUCl3vBMdrns.jpg',
    first_air_date: '2018-07-06',
    genre_ids: [10759, 18, 9648, 16],
    id: 80564,
    name: 'Banana Fish',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'BANANA FISH',
    overview:
      "Nature made Ash Lynx beautiful; nurture made him a cold ruthless killer. A runaway brought up as the adopted heir and sex toy of \"Papa\" Dino Golzine, Ash, now at the rebellious age of seventeen, forsakes the kingdom held out by the devil who raised him. But the hideous secret that drove Ash's older brother mad in Vietnam has suddenly fallen into Papa's insatiably ambitious hands—and it's exactly the wrong time for Eiji Okamura, a pure-hearted young photographer from Japan, to make Ash Lynx's acquaintance...",
    popularity: 68.377,
    poster_path: '/1UV5di9UIXwrpCW3xQ4RNli5hEV.jpg',
    vote_average: 8.9,
    vote_count: 585,
  },
  {
    backdrop_path: '/x6jWDL4H9TaBLGEvyej0qKiirBU.jpg',
    first_air_date: '2014-10-10',
    genre_ids: [16, 35, 18],
    id: 61663,
    name: 'Your Lie in April',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '四月は君の嘘',
    overview:
      "Kousei Arima was a genius pianist until his mother's sudden death took away his ability to play. Each day was dull for Kousei. But, then he meets a violinist named Kaori Miyazono who has an eccentric playing style. Can the heartfelt sounds of the girl's violin lead the boy to play the piano again?",
    popularity: 42.623,
    poster_path: '/IGbeFv5Ji4W0x530JcSHiQpamY.jpg',
    vote_average: 8.9,
    vote_count: 558,
  },
  {
    backdrop_path: '/2f8OLO6UYp78dIQMs0oi7ja15Bl.jpg',
    first_air_date: '2010-04-02',
    genre_ids: [16, 35, 18],
    id: 65648,
    name: 'Maid Sama!',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '会長はメイド様！',
    overview:
      'Misaki Ayuzawa is the first female student council president at a once all-boys school turned co-ed. She rules the school with strict discipline demeanor. But she has a secret—she works at a maid cafe due to her families circumstances. One day the popular A-student and notorious heart breaker Takumi Usui finds out her secret and makes a deal with her to keep it hush from the school in exchange for spending some time with him.',
    popularity: 33.12,
    poster_path: '/igkn0M1bgMeATz59LShvVxZNdVd.jpg',
    vote_average: 8.9,
    vote_count: 405,
  },
  {
    backdrop_path: '/sf7NCqyVUNoyjYuwW5oJke1T1lH.jpg',
    first_air_date: '2021-02-20',
    genre_ids: [10759, 35, 18],
    id: 117376,
    name: 'Vincenzo',
    origin_country: ['KR'],
    original_language: 'ko',
    original_name: '빈센조',
    overview:
      'Vincenzo Cassano is an Italian lawyer and Mafia consigliere who moves back to Korea due to a conflict within his organization. He ends up crossing paths with a sharp-tongued lawyer named Cha-young, and the two join forces in using villainous methods to take down villains who cannot be punished by the law.',
    popularity: 91.505,
    poster_path: '/dvXJgEDQXhL9Ouot2WkBHpQiHGd.jpg',
    vote_average: 8.9,
    vote_count: 317,
  },
  {
    backdrop_path: '/mWwWhDiQWONiSS4Go12TTjNw0E5.jpg',
    first_air_date: '2016-10-06',
    genre_ids: [16, 35, 18],
    id: 68129,
    name: 'Yuri!!! on Ice',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'ユーリ!!! on ICE',
    overview:
      "Yūri Katsuki carried all of Japan's hopes on his shoulders to win at the Gran Prix Finale ice skating competition, but suffered a crushing defeat. He returns home to Kyushu and half feels like he wants to retire, and half feels like he wants to continue ice skating. Suddenly the five-time consecutive world championship ice skater Victor Nikiforov appears before him with Yuri Plisetsky, a young Russian figure skater who is already defeating his seniors. Victor and both Yuris take up the challenge on an unprecedented Gran Prix series.",
    popularity: 27.21,
    poster_path: '/oKVFf2uNCLMsovWBxAW14MmhHUm.jpg',
    vote_average: 8.9,
    vote_count: 435,
  },
  {
    backdrop_path: '/rXXC22YUo31QfOsavy0jUbqdxFc.jpg',
    first_air_date: '2014-12-09',
    genre_ids: [10765, 10759, 16],
    id: 73055,
    name: 'Attack on Titan: No Regrets',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '進撃の巨人 悔いなき選択',
    overview:
      "Many years before becoming the famed captain of the Survey Corps, a young Levi struggles to survive in the capital's garbage dump, the Underground. As the boss of his own criminal operation, Levi attempts to get by with meager earnings while aided by fellow criminals, Isabel Magnolia and Farlan Church. With little hope for the future, Levi accepts a deal from the anti-expedition faction leader Nicholas Lobov, who promises the trio citizenship aboveground if they are able to successfully assassinate Erwin Smith, a squad leader of the Survey Corps.",
    popularity: 84.717,
    poster_path: '/xGdz67d5WHIU7kIqVHO2TxIpmhZ.jpg',
    vote_average: 8.9,
    vote_count: 1597,
  },
  {
    backdrop_path: '/dwEkNoGFZJWqiwJrnzVfmtmVhfU.jpg',
    first_air_date: '2019-01-11',
    genre_ids: [16, 35, 18],
    id: 84669,
    name: 'The Quintessential Quintuplets',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '五等分の花嫁',
    overview:
      'Fuutarou Uesugi is a poor, antisocial ace student who one day meets the rich transfer student Itsuki Nakano. They argue but when Uesugi realizes he is to be her tutor, he tries to get on better terms. While trying to do so he meets four other girls.',
    popularity: 104.358,
    poster_path: '/mrahUSmFjae8UHtlOcZ58ytmAGu.jpg',
    vote_average: 8.9,
    vote_count: 419,
  },
  {
    backdrop_path: '/dJ8yrSokdTMnhKJw06MllSfCegb.jpg',
    first_air_date: '2019-01-12',
    genre_ids: [16, 35, 18],
    id: 83121,
    name: 'Kaguya-sama: Love is War',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'かぐや様は告らせたい～天才たちの恋愛頭脳戦～',
    overview:
      "Considered a genius due to having the highest grades in the country, Miyuki Shirogane leads the prestigious Shuchiin Academy's student council as its president, working alongside the beautiful and wealthy vice president Kaguya Shinomiya. The two are often regarded as the perfect couple by students despite them not being in any sort of romantic relationship.",
    popularity: 66.528,
    poster_path: '/5khbC6AuNgnvnoDbjIMKCOhEtIc.jpg',
    vote_average: 8.9,
    vote_count: 395,
  },
  {
    backdrop_path: '/4sSzTvk200BQyYjRJq69mLwE9xG.jpg',
    first_air_date: '2018-04-25',
    genre_ids: [16, 35, 18, 10759],
    id: 79141,
    name: 'Scissor Seven',
    origin_country: ['CN'],
    original_language: 'zh',
    original_name: '刺客伍六七',
    overview:
      'Seeking to recover his memory, a scissor-wielding, hairdressing, bungling quasi-assassin stumbles into a struggle for power among feuding factions.',
    popularity: 93.226,
    poster_path: '/A39DWUIrf9WDRHCg7QTR8seWUvi.jpg',
    vote_average: 8.9,
    vote_count: 222,
  },
  {
    backdrop_path: '/sWghoJDqMRHDnkmk7fr3By5XPnf.jpg',
    first_air_date: '2019-10-05',
    genre_ids: [16, 35, 10765],
    id: 91801,
    name: 'Welcome to Demon School! Iruma-kun',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '魔入りました！入間くん',
    overview:
      'Fourteen-year-old Suzuki Iruma has just been abandoned and sold to a demon by his irresponsible parents! Surprisingly, the next thing he knows he\'s living with the demon who has adopted him as his new grandson, and has been transferred into a school in the demon world where his new "demon" grandfather works as the principal. Thus begins the cowardly Iruma-kun\'s extraordinary school life among the otherworldly as he faces his true self, takes on challenges, and rises to become someone great.',
    popularity: 63.805,
    poster_path: '/aed6I1EMR4Lbk8bdikWrndbn5Og.jpg',
    vote_average: 8.9,
    vote_count: 140,
  },
];

export const searchTvData = [
  {
    backdrop_path: '/3xF78MnaTAoX3hkygglbCUEywU.jpg',
    first_air_date: '2021-09-17',
    genre_ids: [10759, 9648, 18],
    id: 93405,
    name: 'Squid Game',
    origin_country: ['KR'],
    original_language: 'ko',
    original_name: '오징어 게임',
    overview:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes.",
    popularity: 13496.167,
    poster_path: '/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
    vote_average: 7.9,
    vote_count: 5726,
  },
  {
    backdrop_path: '/wvdWb5kTQipdMDqCclC6Y3zr4j3.jpg',
    first_air_date: '2010-10-31',
    genre_ids: [10759, 18, 10765],
    id: 1402,
    name: 'The Walking Dead',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'The Walking Dead',
    overview:
      "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
    popularity: 1189.779,
    poster_path: '/w21lgYIi9GeUH5dO8l3B9ARZbCB.jpg',
    vote_average: 8.1,
    vote_count: 11761,
  },
  {
    backdrop_path: '/bKxiLRPVWe2nZXCzt6JPr5HNWYm.jpg',
    first_air_date: '2020-12-10',
    genre_ids: [18, 9648, 10759, 10765],
    id: 110316,
    name: 'Alice in Borderland',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '今際の国のアリス',
    overview:
      'With his two friends, a video-game-obsessed young man finds himself in a strange version of Tokyo where they must compete in dangerous games to win.',
    popularity: 478.513,
    poster_path: '/20mOwAAPwZ1vLQkw0fvuQHiG7bO.jpg',
    vote_average: 8.2,
    vote_count: 467,
  },
  {
    backdrop_path: '/hTExot1sfn7dHZjGrk0Aiwpntxt.jpg',
    first_air_date: '2014-03-19',
    genre_ids: [10765, 18, 10759],
    id: 48866,
    name: 'The 100',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'The 100',
    overview:
      "100 years in the future, when the Earth has been abandoned due to radioactivity, the last surviving humans live on an ark orbiting the planet — but the ark won't last forever. So the repressive regime picks 100 expendable juvenile delinquents to send down to Earth to see if the planet is still habitable.",
    popularity: 324.654,
    poster_path: '/wcaDIAG1QdXQLRaj4vC1EFdBT2.jpg',
    vote_average: 7.9,
    vote_count: 6553,
  },
  {
    backdrop_path: '/zrMCOQnzIgGyBtGCdMPom9bOw0r.jpg',
    first_air_date: '2015-08-23',
    genre_ids: [10759, 18],
    id: 62286,
    name: 'Fear the Walking Dead',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Fear the Walking Dead',
    overview:
      'What did the world look like as it was transforming into the horrifying apocalypse depicted in "The Walking Dead"? This spin-off set in Los Angeles, following new characters as they face the beginning of the end of the world, will answer that question.',
    popularity: 305.457,
    poster_path: '/upmd11A2ZaZEG1j6wRGdD4B5cxs.jpg',
    vote_average: 7.7,
    vote_count: 3816,
  },
  {
    backdrop_path: '/hS0IN656SbRe23TyH0PdaGytIuL.jpg',
    first_air_date: '2020-10-04',
    genre_ids: [18, 10765, 9648],
    id: 94305,
    name: 'The Walking Dead: World Beyond',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'The Walking Dead: World Beyond',
    overview:
      'A heroic group of teens sheltered from the dangers of the post-apocalyptic world receive a message that inspires them to leave the safety of the only home they have ever known and embark on a cross-country journey to find the one man who can possibly save the world.',
    popularity: 258.346,
    poster_path: '/6HanIV2hTLE2w7A5bI1KJb3bTL7.jpg',
    vote_average: 7.7,
    vote_count: 810,
  },
  {
    backdrop_path: '/iq5L971DFW1SwLJdvl7OpPI1QeZ.jpg',
    first_air_date: '2021-06-17',
    genre_ids: [16, 10759, 10765],
    id: 114868,
    name: 'Record of Ragnarok',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '終末のワルキューレ',
    overview:
      'Before eradicating humankind from the world, the gods give them one last chance to prove themselves worthy of survival. Let the Ragnarok battles begin.',
    popularity: 248.995,
    poster_path: '/kTs2WNZOukpWdNhoRlH94pSJ3xf.jpg',
    vote_average: 8.7,
    vote_count: 796,
  },
  {
    backdrop_path: '/clsLGcG4OWy1FMywOS0yUXWLWVE.jpg',
    first_air_date: '2021-08-01',
    genre_ids: [16, 35, 10765],
    id: 123446,
    name: 'The Great Jahy Will Not Be Defeated!',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'ジャヒー様はくじけない！',
    overview:
      "The Great Jahy, the Dark Realm's second-in-command, cuts a frightening figure, feared and revered by all. But when a run-in with a magical girl results in the destruction of the precious mana crystal, the Dark Realm falls, transporting the newly tiny and powerless Jahy to the human world! Unfortunately, plotting the revival of the Dark Realm from a cramped, crumbling one-room apartment is no easy feat when you have rent to pay and a job to keep!",
    popularity: 166.949,
    poster_path: '/9hrlzVgSK0y2sA6Q3Nk8oSOIYUD.jpg',
    vote_average: 7.6,
    vote_count: 11,
  },
  {
    backdrop_path: '/xOi6lRbJh3fBFur8QuxTyGzOqiH.jpg',
    first_air_date: '2021-07-13',
    genre_ids: [16, 18, 9648, 10759, 10765],
    id: 112940,
    name: 'Battle Game in 5 Seconds',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '出会って5秒でバトル',
    overview:
      'It was just a usual morning.\n\nAkira Shiroyanagi, a high schooler who loves games and Konpeito (Japanese sweets), has suddenly been dragged into a battlefield by a mysterious girl who calls herself Mion. The participants are told that they are "erased from the family register, involved in an experiment, and gained certain powers."\n\nAkira is determined to win the game with his newfound powers and destroy the organization. Armed with a power no one expects and his "brain" skills, the new period of intelligence battle begins!',
    popularity: 115.242,
    poster_path: '/nGuTtEc5q3pO6Kl2Pmszc9IwEe.jpg',
    vote_average: 7.8,
    vote_count: 6,
  },
  {
    backdrop_path: '/ciPDoPMqd3icCBHsIlhIb3UyOd2.jpg',
    first_air_date: '2021-07-07',
    genre_ids: [16, 10765, 10759, 35],
    id: 111819,
    name: 'Tsukimichi -Moonlit Fantasy-',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '月が導く異世界道中',
    overview:
      'Makoto Misumi is just an ordinary high school student living a regular life, but all of a sudden gets summoned to the other world to become a "hero." The goddess of the other world, however, insults him for being different and strips his "hero" title, before casting him off to the wilderness at the edge of the world. As he wanders the wilderness, Makoto encounters dragons, spiders, orcs, dwarves, and all sorts of non-human tribes. Because Makoto comes from a different world, he is able to unleash unimaginable magical powers and combat skills. But just how will he handle his encounters with various species and survive in his new environment. In this fantasy, Makoto tries to transform the other world into a better place despite the humans and gods having turned their backs on him.',
    popularity: 101.024,
    poster_path: '/oGTihBVxHROSWa1WJnireCbl0KQ.jpg',
    vote_average: 8.5,
    vote_count: 11,
  },
  {
    backdrop_path: '/11Pfh4yqjKbOgn5vY3AQD9VU4Vc.jpg',
    first_air_date: '2019-10-10',
    genre_ids: [16, 18],
    id: 90937,
    name: 'BEASTARS',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'ビースターズ',
    overview:
      'In a world where beasts of all kinds coexist, a gentle wolf awakens to his own predatory urges as his school deals with a murder within its midst.',
    popularity: 90.643,
    poster_path: '/zKEFedE4KEUWdfPvjVC9G1VyEoK.jpg',
    vote_average: 8.7,
    vote_count: 812,
  },
  {
    backdrop_path: '/7goeSggajsAa96CHG48vWrJz2o2.jpg',
    first_air_date: '2011-10-21',
    genre_ids: [10764],
    id: 52910,
    name: 'Law of the Jungle',
    origin_country: ['KR'],
    original_language: 'ko',
    original_name: '정글의 법칙',
    overview:
      'Law of the Jungle is a hybrid reality show combining elements of drama and documentary. The show is hosted by comedian Kim Byung Man, and each episode invites various celebrities from the various field. So far, many of idol stars and famous actors have appeared on the show. The show introduces viewers to exotic locations around the world where celebrities must work together in order to complete missions and survive. The cast celebrities travel to less habituated, natural places to survive on their own and experience life with local tribes and people. In each location, the guests are tasked to hunt and prepare their meals and also create shelter for the tribe. They sometimes confronted by many difficult challenges. Where will the tribe visit? And how will they survive on their own? Stay tuned to check out!',
    popularity: 123.127,
    poster_path: '/qG2JpIDuYhuQOMSLqmMtHBBbfx5.jpg',
    vote_average: 7,
    vote_count: 3,
  },
  {
    backdrop_path: '/smj3Qr0ubJfAchgDRTDT1r2nPZo.jpg',
    first_air_date: '2021-07-16',
    genre_ids: [16, 18, 9648, 10765],
    id: 124396,
    name: 'Sonny Boy',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'Sonny Boy',
    overview:
      'On August 16, midway through a seemingly endless summer vacation, middle school third-year student Nagara, the mysterious transfer student Nozomi, and classmates such as Mizuho and Asakaze, are suddenly transported from their tranquil daily lives to a school adrift in an alternate dimension. They must survive with the super powers that have awakened within them.',
    popularity: 70.613,
    poster_path: '/jCM8zNdcl6lihGGR3vw18Kwk9ZY.jpg',
    vote_average: 9.3,
    vote_count: 3,
  },
  {
    backdrop_path: '/pYErfWWb52zq9QQFoZ0Qeoo5Yz.jpg',
    first_air_date: '2014-09-12',
    genre_ids: [9648, 10759, 18],
    id: 61345,
    name: 'Z Nation',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Z Nation',
    overview:
      'Three years after the zombie virus has gutted the country, a team of everyday heroes must transport the only known survivor of the plague from New York to California, where the last functioning viral lab waits for his blood.',
    popularity: 90.887,
    poster_path: '/gXfeDMkEcHoYBvtkbU11g3F81b.jpg',
    vote_average: 7.1,
    vote_count: 580,
  },
  {
    backdrop_path: '/uAjMQlbPkVHmUahhCouANlHSDW2.jpg',
    first_air_date: '2019-01-11',
    genre_ids: [16, 9648, 10765, 10759, 18],
    id: 83097,
    name: 'The Promised Neverland',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '約束のネバーランド',
    overview:
      'Surrounded by a forest and a gated entrance, the Grace Field House is inhabited by orphans happily living together as one big family, looked after by their "Mama," Isabella. Although they are required to take tests daily, the children are free to spend their time as they see fit, usually playing outside, as long as they do not venture too far from the orphanage — a rule they are expected to follow no matter what. However, all good times must come to an end, as every few months, a child is adopted and sent to live with their new family... never to be heard from again.\n\nHowever, the three oldest siblings have their suspicions about what is actually happening at the orphanage, and they are about to discover the cruel fate that awaits the children living at Grace Field, including the twisted nature of their beloved Mama.',
    popularity: 71.727,
    poster_path: '/oBgRCpAbtMpk1v8wfdsIph7lPQE.jpg',
    vote_average: 9,
    vote_count: 699,
  },
  {
    backdrop_path: '/i4E5njHqg0QyhANBnlZMxRkMosq.jpg',
    first_air_date: '2021-07-01',
    genre_ids: [16, 10759, 10765],
    id: 121131,
    name: 'Scarlet Nexus',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'SCARLET NEXUS',
    overview:
      'Saved by the Other Suppression Force as a child, psychokinetic Yuito enlists in this elite team formed to fight Earth’s enemy. Meanwhile, prodigy Kasane was scouted for her abilities. Kasane’s dreams tell her strange things, dragging the two into an unavoidable fate.',
    popularity: 69.563,
    poster_path: '/oiuyTyGKrim6iUIP37WHV3uGmv3.jpg',
    vote_average: 6.3,
    vote_count: 3,
  },
  {
    backdrop_path: '/qmeC99iX9YPbxi3Dwsw5VvxIbCC.jpg',
    first_air_date: '2021-04-12',
    genre_ids: [16, 18, 10759, 10765],
    id: 97525,
    name: 'To Your Eternity',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '不滅のあなたへ',
    overview:
      'In the beginning, an "orb" is cast unto Earth. "It" can do two things: change into the form of the thing that stimulates "it"; and come back to life after death. "It" morphs from orb to rock, then to wolf, and finally to boy, but roams about like a newborn who knows nothing. As a boy, "it" becomes Fushi. Through encounters with human kindness, Fushi not only gains survival skills, but grows as a "person". But his journey is darkened by the inexplicable and destructive enemy Nokker, as well as cruel partings with the people he loves.',
    popularity: 62.207,
    poster_path: '/lA2jRBubr2OLOlbkJXuBXYqv4A9.jpg',
    vote_average: 8.3,
    vote_count: 63,
  },
  {
    backdrop_path: '/4YnAZ1KO9goeS4c06VO7HXiO3oO.jpg',
    first_air_date: '2014-07-13',
    genre_ids: [10765, 18, 9648],
    id: 47640,
    name: 'The Strain',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'The Strain',
    overview:
      'A high concept thriller that tells the story of Dr. Ephraim Goodweather, the head of the Center for Disease Control Canary Team in New York City. He and his team are called upon to investigate a mysterious viral outbreak with hallmarks of an ancient and evil strain of vampirism. As the strain spreads, Eph, his team, and an assembly of everyday New Yorkers, wage war for the fate of humanity itself.',
    popularity: 54.194,
    poster_path: '/2BWErT9QcADpf2G4BZ769eSnFTP.jpg',
    vote_average: 7.5,
    vote_count: 1253,
  },
  {
    backdrop_path: '/mpbLQla2rkFjgouzWAHpAZPSfwR.jpg',
    first_air_date: '2021-02-25',
    genre_ids: [16, 9648, 10759],
    id: 112163,
    name: 'High-Rise Invasion',
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '天空侵犯',
    overview:
      "High-school girl Yuri suddenly finds herself on the rooftop of a high-rise building. She's trapped in a bizarre world surrounded by skyscrapers, where a masked man cracked open a man's head with an axe before her eyes. Finding a way to survive this bizarre world, find her beloved brother, and escape becomes her top priority, but she is beset by danger not just from the mysterious Masks, which possess both inhuman strength and cruelty, but other survivors turned cruel or desparate by the insanity of the high-rise world.",
    popularity: 56.651,
    poster_path: '/5uXaWe0LXTpBQVBBXL1ynae1DED.jpg',
    vote_average: 8.4,
    vote_count: 482,
  },
  {
    backdrop_path: '/uPHXbrh9jlq2XgfjjTFlkJfgtOQ.jpg',
    first_air_date: '2021-07-08',
    genre_ids: [16, 18, 10759, 10765],
    id: 110642,
    name: 'Resident Evil: Infinite Darkness',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Resident Evil: Infinite Darkness',
    overview:
      'Years after the horrors of Raccoon City, Leon and Claire find themselves consumed by a dark conspiracy when a viral attack ravages the White House.',
    popularity: 46.832,
    poster_path: '/xCHJq63FrXCJAF7v69Obd24siDF.jpg',
    vote_average: 8,
    vote_count: 426,
  },
];

export const searchMovieData = [
  {
    adult: false,
    backdrop_path: '/9K2j6pinRuyWxWEWMTpbjSlsn6F.jpg',
    genre_ids: [18],
    id: 166666,
    original_language: 'de',
    original_title: '3096 Tage',
    overview:
      'A young Austrian girl is kidnapped and held in captivity for eight years. Based on the real-life case of Natascha Kampusch.',
    popularity: 36.357,
    poster_path: '/jQ7aucozEWiz1cBCdZtcYSJfWC7.jpg',
    release_date: '2013-02-21',
    title: '3096 Days',
    video: false,
    vote_average: 7.4,
    vote_count: 585,
  },
  {
    adult: false,
    backdrop_path: '/4OrW7cqYrABIYbJHoVZUpE8AH1h.jpg',
    genre_ids: [27, 9648],
    id: 2667,
    original_language: 'en',
    original_title: 'The Blair Witch Project',
    overview:
      'In October of 1994 three student filmmakers disappeared in the woods near Burkittsville, Maryland, while shooting a documentary. A year later their footage was found.',
    popularity: 39.49,
    poster_path: '/9050VGrYjYrEjpOvDZVAngLbg1f.jpg',
    release_date: '1999-07-14',
    title: 'The Blair Witch Project',
    video: false,
    vote_average: 6.3,
    vote_count: 3440,
  },
  {
    adult: false,
    backdrop_path: '/nKMeTdm72LQ756Eq20uTjF1zDXu.jpg',
    genre_ids: [12, 18],
    id: 399360,
    original_language: 'en',
    original_title: 'Alpha',
    overview:
      'In the prehistoric past, Keda, a young and inexperienced hunter, struggles to return home after being separated from his tribe when bison hunting goes awry. On his way back he will find an unexpected ally.',
    popularity: 46.07,
    poster_path: '/afdZAIcAQscziqVtsEoh2PwsYTW.jpg',
    release_date: '2018-08-17',
    title: 'Alpha',
    video: false,
    vote_average: 6.4,
    vote_count: 2026,
  },
  {
    adult: false,
    backdrop_path: '/2zg3nm55gMUi5lFzCdXMjnYJjS9.jpg',
    genre_ids: [12, 28, 27, 53],
    id: 11237,
    original_language: 'en',
    original_title: 'Anacondas: The Hunt for the Blood Orchid',
    overview:
      "The blood orchid - a rare flower that could hold the secret of eternal life and be worth a fortune to the company that finds it. Led by a pharmaceutical research team, a scientific expedition sets out to explore deep into the jungles of Borneo to locate and bring back samples of the legendary plant. Battling through rainstorms to make their way upriver, the group encounters poisonous insects and a ferocious crocodile, only to discover they're being stalked by an even greater danger: a gathering of giant anacondas! Heat-sensing, fifty-foot-long flesh-eaters that'll go after anyone that crosses their path!",
    popularity: 35.257,
    poster_path: '/gTlVy3wUApAanIAPdx3yz0YOROD.jpg',
    release_date: '2004-08-26',
    title: 'Anacondas: The Hunt for the Blood Orchid',
    video: false,
    vote_average: 5.4,
    vote_count: 676,
  },
  {
    adult: false,
    backdrop_path: '/29BCwmpV9HQUekAGlJLplkslRRf.jpg',
    genre_ids: [27, 9648],
    id: 588,
    original_language: 'en',
    original_title: 'Silent Hill',
    overview:
      "In search for answers, a mother travels to the enigmatic town of Silent Hill when her daughter begins to suffer recurring nightmares related to the place. It doesn't take long for her to discover its home to beings as equally haunting as the town itself.",
    popularity: 43.703,
    poster_path: '/bQkXL0cSlPviaQhxM090knCc5kS.jpg',
    release_date: '2006-04-21',
    title: 'Silent Hill',
    video: false,
    vote_average: 6.5,
    vote_count: 3169,
  },
  {
    adult: false,
    backdrop_path: '/kdSsUC9DpREwFFPeqPgAaxzE3UT.jpg',
    genre_ids: [10752, 28, 18],
    id: 374720,
    original_language: 'en',
    original_title: 'Dunkirk',
    overview:
      'The story of the miraculous evacuation of Allied soldiers from Belgium, Britain, Canada and France, who were cut off and surrounded by the German army from the beaches and harbour of Dunkirk between May 26th and June 4th 1940 during World War II.',
    popularity: 37.139,
    poster_path: '/ebSnODDg9lbsMIaWg2uAbjn7TO5.jpg',
    release_date: '2017-07-19',
    title: 'Dunkirk',
    video: false,
    vote_average: 7.5,
    vote_count: 13259,
  },
  {
    adult: false,
    backdrop_path: '/nH6hPhJq3EEv9CnBZgXU3IQnpJo.jpg',
    genre_ids: [12, 53, 878],
    id: 74,
    original_language: 'en',
    original_title: 'War of the Worlds',
    overview:
      'Ray Ferrier is a divorced dockworker and less-than-perfect father. Soon after his ex-wife and her new husband drop off his teenage son and young daughter for a rare weekend visit, a strange and powerful lightning storm touches down.',
    popularity: 32.75,
    poster_path: '/oZmJ6hD2dc6zLCIPgw8onPMo0QC.jpg',
    release_date: '2005-06-28',
    title: 'War of the Worlds',
    video: false,
    vote_average: 6.5,
    vote_count: 6443,
  },
  {
    adult: false,
    backdrop_path: '/dVr11o9or7AS8AMPfwjSpEU83iU.jpg',
    genre_ids: [18, 10752],
    id: 423,
    original_language: 'en',
    original_title: 'The Pianist',
    overview:
      "The true story of pianist Władysław Szpilman's experiences in Warsaw during the Nazi occupation. When the Jews of the city find themselves forced into a ghetto, Szpilman finds work playing in a café; and when his family is deported in 1942, he stays behind, works for a while as a laborer, and eventually goes into hiding in the ruins of the war-torn city.",
    popularity: 30.894,
    poster_path: '/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg',
    release_date: '2002-09-17',
    title: 'The Pianist',
    video: false,
    vote_average: 8.4,
    vote_count: 6683,
  },
  {
    adult: false,
    backdrop_path: '/7teoHvDIKJ8IN7FdVGFM4XdaQZd.jpg',
    genre_ids: [53],
    id: 345009,
    original_language: 'en',
    original_title: 'Mine',
    overview:
      'After a failed assassination attempt, a soldier finds himself stranded in the desert. Exposed to the elements, he must survive the dangers of the desert and battle the psychological and physical toll of the treacherous conditions.',
    popularity: 30.132,
    poster_path: '/xfQV6nTH6zpvhmdcTOoBR2Q4Z2M.jpg',
    release_date: '2016-10-06',
    title: 'Mine',
    video: false,
    vote_average: 6.6,
    vote_count: 1036,
  },
  {
    adult: false,
    backdrop_path: '/nw1wEmAcfVjRGRQbcLAYGeBqviV.jpg',
    genre_ids: [27, 18, 53],
    id: 332567,
    original_language: 'en',
    original_title: 'The Shallows',
    overview:
      "When Nancy is surfing on a secluded beach, she finds herself on the feeding ground of a great white shark. Though she is stranded only 200 yards from shore, survival proves to be the ultimate test of wills, requiring all of Nancy's ingenuity, resourcefulness, and fortitude.",
    popularity: 32.835,
    poster_path: '/bnBV7hZmLuA0Si5Aop481sPF2RY.jpg',
    release_date: '2016-06-24',
    title: 'The Shallows',
    video: false,
    vote_average: 6.4,
    vote_count: 4210,
  },
  {
    adult: false,
    backdrop_path: '/rInMNJipAil3iIcBltPiGRkNAG7.jpg',
    genre_ids: [27, 53],
    id: 672741,
    original_language: 'en',
    original_title: 'Till Death',
    overview:
      "After a romantic evening at their secluded lake house, a woman wakes up handcuffed to her dead husband. Trapped and isolated in the dead of winter, she must fight off hired killers to escape her late spouse's twisted plan.",
    popularity: 34.87,
    poster_path: '/bvwMvrX2XqZVOz35YuYbFx3Iggr.jpg',
    release_date: '2021-07-02',
    title: 'Till Death',
    video: false,
    vote_average: 6.7,
    vote_count: 186,
  },
  {
    adult: false,
    backdrop_path: '/rspbS1E9wJtslrb8amfJgtMBUVh.jpg',
    genre_ids: [28, 27],
    id: 924,
    original_language: 'en',
    original_title: 'Dawn of the Dead',
    overview:
      'A group of survivors take refuge in a shopping mall after the world is taken over by aggressive, flesh-eating zombies.',
    popularity: 37.373,
    poster_path: '/iBLQATsIkv005fvIhhbM4MvqhYp.jpg',
    release_date: '2004-03-19',
    title: 'Dawn of the Dead',
    video: false,
    vote_average: 7,
    vote_count: 2901,
  },
  {
    adult: false,
    backdrop_path: '/7ELIOvgJhhGDenPhdwRqi8RGIuL.jpg',
    genre_ids: [28, 27, 53],
    id: 14863,
    original_language: 'en',
    original_title: 'Anaconda 3: Offspring',
    overview:
      "Cancer-terminal tycoon Peter Murdoch's secret Wexel Hall Pharmaceuticals lab has developed a blood orchid extract cure. To examine why it works optimally in snakes, they also bread a super-anaconda strain. But the original pair escapes, leaving a bloody trail of corpses. Murdoch runs, instructing his staff to clean up. They keep failing and being eaten like unsuspecting locals, some alive, even after enlisting ruthless big game hunter Hammett. The fast-growing pregnant monster sheds its skin, thus disabling the only tracking device.",
    popularity: 28.628,
    poster_path: '/ce2z5H6gS6mc54kpnFj9G0xjH4G.jpg',
    release_date: '2008-01-01',
    title: 'Anaconda 3: Offspring',
    video: false,
    vote_average: 4.8,
    vote_count: 208,
  },
  {
    adult: false,
    backdrop_path: '/sizHX5VbwlBihaathTQHVGk1jdi.jpg',
    genre_ids: [878, 18, 10749, 28],
    id: 514207,
    original_language: 'ru',
    original_title: 'Вторжение',
    overview:
      'Two years after the fall of the alien ship, the life of a young woman from Moscow has been changed forever. Her growing powers are now at the focus of both human and celestial investigation: an alien force takes an interest in her, and will stop short of nothing, including an invasion. Can love and compassion save humanity, when faced with a much greater and more demanding test this time?',
    popularity: 26.049,
    poster_path: '/dqKqzcdhtJwOhjqe89RTURqILtl.jpg',
    release_date: '2020-01-01',
    title: 'Invasion',
    video: false,
    vote_average: 6.9,
    vote_count: 576,
  },
  {
    adult: false,
    backdrop_path: '/zbdJczDXVpVLXe5FMLWQlz3P4Bw.jpg',
    genre_ids: [35],
    id: 205724,
    original_language: 'en',
    original_title: 'Welcome to the Jungle',
    overview: 'A company retreat on a tropical island goes terribly awry.',
    popularity: 38.087,
    poster_path: '/wRHaPGBBmQhUVgYofPoaqTEdUWq.jpg',
    release_date: '2013-04-27',
    title: 'Welcome to the Jungle',
    video: false,
    vote_average: 5.1,
    vote_count: 317,
  },
  {
    adult: false,
    backdrop_path: '/iHJQIKSLHN2mUUWySpj2MO5HVtS.jpg',
    genre_ids: [27, 18, 53, 14],
    id: 527261,
    original_language: 'en',
    original_title: 'The Silence',
    overview:
      'With the world under attack by deadly creatures who hunt by sound, a teen and her family seek refuge outside the city and encounter a mysterious cult.',
    popularity: 23.743,
    poster_path: '/lTVOquzxw2DPF3MKuYd1ynz9F6H.jpg',
    release_date: '2019-05-16',
    title: 'The Silence',
    video: false,
    vote_average: 6.1,
    vote_count: 1085,
  },
  {
    adult: false,
    backdrop_path: '/tav8VVa6H6KooK5rFhAG2jT5ZNx.jpg',
    genre_ids: [12, 18, 53],
    id: 390062,
    original_language: 'en',
    original_title: 'Jungle',
    overview:
      'In 1981, an enthusiastic young adventurer follows his dreams into the Bolivian Amazon jungle with two friends and a guide with a mysterious past. Their journey quickly turns into a terrifying ordeal as the darkest elements of human nature and the deadliest threats of the wilderness lead to an all-out fight for survival.',
    popularity: 28.962,
    poster_path: '/tDgxknTVwrScxpCYyGUjXSn5NRk.jpg',
    release_date: '2017-06-27',
    title: 'Jungle',
    video: false,
    vote_average: 6.5,
    vote_count: 1443,
  },
  {
    adult: false,
    backdrop_path: '/PN7yjmQdmG0J62jsrtmrPi8ezK.jpg',
    genre_ids: [27, 53, 878],
    id: 1562,
    original_language: 'en',
    original_title: '28 Weeks Later',
    overview:
      'The inhabitants of the British Isles have lost their battle against the onslaught of disease, as the deadly rage virus has killed every citizen there. Six months later, a group of Americans dare to set foot on the isles, convinced the danger has come and gone. But it soon becomes all too clear that the scourge continues to live, waiting to pounce on its next victims.',
    popularity: 32.526,
    poster_path: '/t5O7QkiKyKcCE3UihKsAjlJ9aF8.jpg',
    release_date: '2007-04-26',
    title: '28 Weeks Later',
    video: false,
    vote_average: 6.6,
    vote_count: 3155,
  },
  {
    adult: false,
    backdrop_path: '/lYfWrvE90OdHh3fNmaSweSHlDl5.jpg',
    genre_ids: [27, 28],
    id: 572609,
    original_language: 'ja',
    original_title: 'がっこうぐらし！',
    overview:
      'Ebisuzawa Kurumi, Takeya Yuki, Wakasa Yuri,  and Naoki Miki all attend the same high school. They also live on campus at the school. The girls enjoy their time at the school until students become infected by a virus and turn into zombies. The girls are surrounded by student zombies and they struggle desperately to survive.',
    popularity: 23.8,
    poster_path: '/i2g0gwmZyQaqnwCIFE6NVXqExMq.jpg',
    release_date: '2019-01-25',
    title: 'School-Live!',
    video: false,
    vote_average: 6.6,
    vote_count: 11,
  },
  {
    adult: false,
    backdrop_path: '/qKVOTKPPtvoXd75L1HOSBPLtKWS.jpg',
    genre_ids: [16, 28, 14, 878],
    id: 761898,
    original_language: 'ja',
    original_title:
      '劇場版 ソードアート・オンライン プログレッシブ 星なき夜のアリア',
    overview:
      "One month after Kayaba Akihiko's game of death began, the death toll continues to rise, two thousand players having already lost their lives to the ultra-difficult VRMMO world of Sword Art Online. On the day of the strategy meeting to plan out the first-floor boss battle, Kirito, a solo player who vows to fight alone to get stronger, runs into a rare, high-level female player. She gracefully dispatches powerful monsters with a single rapier that flashes like a shooting star in the night...",
    popularity: 21.832,
    poster_path: '/ndTpuCStuEcCNNznnTwyGXJRvBn.jpg',
    release_date: '2021-10-30',
    title: 'Sword Art Online: Progressive - Aria of a Starless Night',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
];
